apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    version: gke
  name: guidewire
  namespace: demo
spec:
  selector:
    matchLabels:
      app: guidewire
  template:
    metadata:
      labels:
        version: gke
        app: guidewire
    spec:
      containers:
        - env:
            - name: PORT
              value: "8080"
            - name: LISTEN_ADDR
              value: 0.0.0.0
          name: server
          image: gcr.io/gft-anthos-demo/pc:v8
          imagePullPolicy: Always
          ports:
            - name: liveness-port
              containerPort: 8080
          resources:
            limits:
              cpu: 600m
              memory: 6Gi
            requests:
              cpu: 400m
              memory: 3Gi
      terminationGracePeriodSeconds: 5
